/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.petlog.petlog.ui;

import com.mongodb.client.MongoCollection;
import com.petlog.petlog.service.MongoDBConnect;
import com.petlog.petlog.service.VaksinService;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author LENOVO
 */
public class LaporanTableForm extends javax.swing.JFrame {

    /**
     * Creates new form LaporanTableForm
     */
    public LaporanTableForm() {
        initComponents();
        loadData(); // ⬅️ tampilkan semua data
    }
    
    private void loadData() {
    loadVaksin();
    loadCatatan();
    loadHewan();
}
    private String selectedId = null;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tabPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVaksin = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCatatan = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHewan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 50));

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        tblVaksin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVaksin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVaksinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVaksin);

        tabPane.addTab("Vaksin", jScrollPane1);

        tblCatatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCatatan);

        tabPane.addTab("Catatan", jScrollPane2);

        tblHewan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblHewan);

        tabPane.addTab("Hewan", jScrollPane3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblVaksinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVaksinMouseClicked

    }//GEN-LAST:event_tblVaksinMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int row = tblVaksin.getSelectedRow();
if (row != -1) {
    String id = tblVaksin.getValueAt(row, 0).toString();
    String namaHewan = tblVaksin.getValueAt(row, 1).toString();
    String namaVaksin = tblVaksin.getValueAt(row, 2).toString();
    String tanggal = tblVaksin.getValueAt(row, 3).toString();

    EditVaksin dialog = new EditVaksin(this, id, namaHewan, namaVaksin, tanggal);
    dialog.setVisible(true);

    loadVaksin(); // Refresh tabel setelah dialog ditutup
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            int row = tblVaksin.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus.");
        return;
    }

    String id = tblVaksin.getValueAt(row, 0).toString();

    int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        VaksinService.hapus(id);
        JOptionPane.showMessageDialog(this, "🗑️ Data berhasil dihapus.");
        loadVaksin();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanTableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanTableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanTableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanTableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanTableForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tblCatatan;
    private javax.swing.JTable tblHewan;
    private javax.swing.JTable tblVaksin;
    // End of variables declaration//GEN-END:variables

    private void loadVaksin() {
    DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Nama Hewan", "Nama Vaksin", "Tanggal"}, 0);
    MongoCollection<Document> col = MongoDBConnect.getCollection("jadwal_vaksin");

    for (Document doc : col.find()) {
        model.addRow(new Object[]{
            doc.getObjectId("_id").toHexString(), // Simpan ID sebagai String
            doc.getString("namaHewan"),
            doc.getString("namaVaksin"),
            doc.getString("tanggal")
        });
    }

    tblVaksin.setModel(model);
    
        // Sembunyikan kolom ID (kolom 0)
    tblVaksin.getColumnModel().getColumn(0).setMinWidth(0);
    tblVaksin.getColumnModel().getColumn(0).setMaxWidth(0);
}


    private void loadCatatan() {
    DefaultTableModel model = new DefaultTableModel(new String[]{"Jenis", "Tanggal", "Catatan"}, 0);
    MongoCollection<Document> col = MongoDBConnect.getCollection("catatan_perawatan");

    for (Document doc : col.find()) {
        model.addRow(new Object[]{
            doc.getObjectId("_id").toHexString(), // Simpan ID sebagai String
            doc.getString("jenis"),
            doc.getString("tanggal"),
            doc.getString("catatan")
        });
    }

    tblCatatan.setModel(model);
        // Sembunyikan kolom ID (kolom 0)
    tblCatatan.getColumnModel().getColumn(0).setMinWidth(0);
    tblCatatan.getColumnModel().getColumn(0).setMaxWidth(0);
    
    
    }

    private void loadHewan() {
    DefaultTableModel model = new DefaultTableModel(new String[]{"Nama", "Jenis", "Usia", "Ras", "Catatan"}, 0);
    MongoCollection<Document> col = MongoDBConnect.getCollection("data_hewan");

    for (Document doc : col.find()) {
        model.addRow(new Object[]{
            doc.getObjectId("_id").toHexString(), // Simpan ID sebagai String
            doc.getString("nama"),
            doc.getString("jenis"),
            doc.getString("usia"),
            doc.getString("ras"),
            doc.getString("catatan")
        });
    }

    tblHewan.setModel(model);
        // Sembunyikan kolom ID (kolom 0)
    tblHewan.getColumnModel().getColumn(0).setMinWidth(0);
    tblHewan.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    
    DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Nama Hewan", "Nama Vaksin", "Tanggal"}, 0) {
    public boolean isCellEditable(int row, int column) {
        return column != 0; // ID tidak bisa diedit
    }
};
}
